---

- name: Get InfluxData APT GPG key
  apt_key:
    id: '{{ influxdata__key_id | replace(" ","") }}'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else "hkp://pool.sks-keyservers.net" }}'
    keyring: '/etc/apt/trusted.gpg.d/influxdata.gpg'
    state: 'present'

- name: Configure InfluxData APT repository
  apt_repository:
    repo: '{{ influxdata__repository }}'
    state: 'present'
    update_cache: True

- name: Install InfluxData packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ influxdata__packages }}'
    - '{{ influxdata__group_packages }}'
    - '{{ influxdata__host_packages }}'
    - '{{ influxdata__dependent_packages }}'
  register: influxdata__register_install

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save InfluxData local facts
  template:
    src: 'etc/ansible/facts.d/influxdata.fact.j2'
    dest: '/etc/ansible/facts.d/influxdata.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: influxdata__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: (influxdata__register_facts is changed or
         influxdata__register_install is changed)
