---

- name: Manage InfluxData  APT repositories
  hosts: [ 'debops_service_influxdata' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.influxdata
      tags: [ 'role::influxdata' ]
